### ISSUE TITLE
[question] Will be possible to use this images, or have a diferent one to run Gut in the pipeline? 

### ISSUE THREAD

**Issue by Dracks** [abarichello/godot-ci#119]
Hello, 

I would like to run the godot unit test library in the pipeline, Did you know if it will be possible to run it? 

I tried to run it in gitlab with this image, and of course didn't work because libx11 was not there. 

Thanks,

**Comment by Razzlegames** [comment]
You'd just need to run without GUI, which is easy with `godot` on command line, but just using the `-s` (run a single script) parameter:

I run like this

```bash
godot -s --verbose addons/gut/gut_cmdln.gd --path $PWD -ginclude_subdirs -gdir=res://Tests -gexit -gprefix=test_
```

Note the example YAML I use for my *Godot 3* project. I'm also using an old `GUT` version, but the concept should be the same (running `godot` with a single script)

```yaml
image: barichello/godot-ci:3.5.2

stages:
  - tests
  - export
  - deploy

before_script:
  - mkdir -v -p build/linux
  - mkdir -v -p build/windows
  - mkdir -v -p build/mac
  - mkdir -v -p build/web

unitTests:
  stage: tests
  script:
    - cd Godot/Project
    - find 
    - echo "Init import cache"
    - godot --editor --quit
    - godot -s --verbose addons/gut/gut_cmdln.gd --path $PWD -ginclude_subdirs -gdir=res://Tests -gexit -gprefix=test_

integrationTests:
  stage: tests
  script:
    - cd Godot/Project
    - export GODOT_MODE="headless"
    - godot -v --export-pack "Linux/X11" game.pck 
    - test -e game.pck
    - godot -verbose --main-pack game.pck ./Tests/IntegrationTests/RunAllIntegrationTests.tscn 

linux:
  stage: export
  script:
    - cd Godot/Project
    - godot -v --export "Linux/X11" ../../build/linux/$EXPORT_NAME.x86_64
    - test -e ../../build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME-$CI_COMMIT_BRANCH
    paths:
      - build/linux
    expire_in: 1 day
  only:
      - release
      - master

windows:
  stage: export
  script:
    - cd Godot/Project
    - godot -v --export "Windows Desktop" ../../build/windows/$EXPORT_NAME.exe
    - test -e ../../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME-$CI_COMMIT_BRANCH
    paths:
      - build/windows
    expire_in: 1 day
  only:
      - release
      - master

mac:
  stage: export
  script:
    - cd Godot/Project
    - godot -v --export "Mac OSX" ../../build/mac/$EXPORT_NAME.zip
    - test -e ../../build/mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME-$CI_COMMIT_BRANCH
    paths:
      - build/mac
    expire_in: 1 day
  only:
      - release
      - master

web:
  stage: export
  script:
    - cd Godot/Project
    - godot -v --export "HTML5" ../../build/web/index.html
    - test -e ../../build/web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME-$CI_COMMIT_BRANCH
    paths:
      - build/web
    expire_in: 1 day
  only:
      - release
      - master
```

**Comment by Dracks** [comment]
Hi, sorry for replying late, It didn't work, I've got this file in gitlab:
```

image: barichello/godot-ci:4.1

# pipeline example: https://docs.google.com/document/d/1G9G2JvR3Up8erSdhACT_519OJ1MTQQ9VQmaN2SCx_EA/edit#heading=h.o0671lbdks1f

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - cd godot
    # - godot --editor --quit
    # - godot -s --verbose --path "$PWD" addons/gut/gut_cmdln.gd -gexit
    - godot -s --verbose addons/gut/gut_cmdln.gd --path $PWD -ginclude_subdirs -gdir=res://Tests -gexit -gprefix=test_

```

I've got this error:
```
$ godot -s --verbose addons/gut/gut_cmdln.gd --path $PWD -ginclude_subdirs -gdir=res://Tests -gexit -gprefix=test_
Godot Engine v4.1.stable.official.970459615 - https://godotengine.org/
TextServer: Added interface "Dummy"
TextServer: Added interface "ICU / HarfBuzz / Graphite (Built-in)"
libX11.so.6: cannot open shared object file: No such file or directory
ERROR: Can't load Xlib dynamically.
   at: DisplayServerX11 (platform/linuxbsd/x11/display_server_x11.cpp:5406)
Your video card drivers seem not to support the required Vulkan version.
If possible, consider updating your video card drivers or using the OpenGL 3 driver.
You can enable the OpenGL 3 driver by starting the engine from the
command line with the command:
    "godot" --rendering-driver opengl3
If you recently updated your video card drivers, try rebooting.
ERROR: Unable to create DisplayServer, all display drivers failed.
   at: setup2 (main/main.cpp:2212)
```

What I'm doing wrong?
