### ISSUE TITLE
Unable to load any resources (4.2.1)

### ISSUE THREAD

**Issue by Jodebu** [abarichello/godot-ci#127]
When exporting, the engine is not able to find any of the resources of the project,
The binaries will build, but they will be completely broken when you try to execute them. This issue does not appear on local.

The only thing I can think of is that the `.godot/imported/` folder is not being generated on the expected place, but I am really not sure. Could you please provide where is it supposed to be?

Here is my YAML file:
```yaml
name: "Build and export"
on: 
  push:
    branches:
      - main
      - develop

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: OBMar
  PROJECT_PATH: .
  EXPORT_TYPE: ${{ github.ref_name == 'main' && 'release' || 'debug'}}

jobs:
  export:
    name: Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    strategy: 
      matrix:
        include:
          - os: "windows"
            name: "Windows Desktop"
            extension: "exe"
          - os: "linux"
            name: "Linux/X11"
            extension: "x86_64"
          - os: "mac"
            name: "Mac OSX"
            extension: "zip"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.os }}
          cd $PROJECT_PATH
          godot --headless --verbose --export-${EXPORT_TYPE} "${{ matrix.name }}" build/${{ matrix.os }}/$EXPORT_NAME.${{ matrix.extension }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: build/${{ matrix.os }}
```

And here is an extract from one of the jobs:
![imagen](https://github.com/abarichello/godot-ci/assets/7392472/d29cd9ba-0755-44d2-9a67-49335da9b979)

Thank you very much in advance
