### ISSUE TITLE
Error when exporting project

### ISSUE THREAD

**Issue by Hanksha** [aBARICHELLO/godot-ci#13]
Hi,

It might not be at all an issue of the Docker image but I figured someone might have encountered that issue already.

I'm using Circle CI to export my project for HTML, Windows and macOS. For each of them I'm getting this error when running `godot --export`:

```
ERROR: ~List: Condition "_first != __null" is true.
 
   At: ./core/self_list.h:112.
 
ERROR: cleanup: There are still MemoryPool allocs in use at exit!
 
   At: core/pool_vector.cpp:69.
```

The build still passes and the builds are there but it seems they are broken (I can only test the macOS/HTML one).

When I run `godot --export` on my machine it works fine.

Any idea on what's going on?

This is the Circle CI config file:
```
version: 2.1
jobs:
  build:
    docker: 
      - image: barichello/godot-ci
    steps:
      - checkout
      - run: |
          mkdir -p ./build/chroma-dungeon-browser
          mkdir -p ./build/windows
          mkdir -p ./build/macos
      - run: godot --export windows-desktop ./build/windows/chroma-dungeon.exe
      - run: godot --export macos ./build/macos/chroma-dungeon.dmg
      - run: godot --export html ./build/chroma-dungeon-browser/index.html
      - run: butler push ./build/windows/chroma-dungeon.exe caldera-games/chroma-dungeon:windows
      - run: butler push ./build/macos/chroma-dungeon.dmg caldera-games/chroma-dungeon:macos
      - run: butler push ./build/chroma-dungeon-browser caldera-games/chroma-dungeon:browser
```
