### ISSUE TITLE
Import hangs when using blender assets

### ISSUE THREAD

**Issue by lunarlabs** [abarichello/godot-ci#152]
When running my modified CI script with the Docker image, the process just hangs/deadlocks, with the job eventually timing out. No errors show up on the console.

Here is my gitlab-ci.yml file:

```
image: barichello/godot-ci:4.3

cache:
  key: import-assets
  paths: 
  - '.godot/imported/'

stages:
  - import-assets
  - test
  - export
  - deploy

variables:
  EXPORT_NAME: makina-mongoose
  GIT_SUBMODULE_STRATEGY: recursive

import-assets:
  stage: import-assets
  script:
  - apt-get update
  - apt-get install -y --no-install-recommends xz-utils
  - wget -nv https://mirrors.iu13.net/blender/release/Blender4.1/blender-4.1.1-linux-x64.tar.xz
  - tar -xf blender-4.1.1-linux-x64.tar.xz
  - cd blender-4.1.1-linux-x64
  - touch .gdignore
  - pwd | sed 's/^/filesystem\/import\/blender\/blender_path = \"/;s/$/"/' >> ~/.config/godot/editor_settings-4.tres
  - cd ..
  - mkdir -p .godot
  - godot --headless --verbose --import
  when: manual
```
