### ISSUE TITLE
GDExtension Support With Export?

### ISSUE THREAD

**Issue by Cable-Billing** [abarichello/godot-ci#163]
I'm trying to export my project using this as a GitHub action and I'm running into a issue where it doesn't know what `Steam` and `SteamMultiplayerPeer` is.

I'm not using the Godot-Steam editor and instead using the `GodotSteam` and `SteamMultiplayerPeer` GDExtensions.

- [GodotSteam GDExtension 4.1 / 4.2 / 4.3](https://godotengine.org/asset-library/asset/2258)
- [Steam Multiplayer Peer](https://godotengine.org/asset-library/asset/2445)

I can export okay on my local machine using the Godot 4.3 Stable version with the Godot-Steam custom export templates.

```
SCRIPT ERROR: Parse Error: Identifier "Steam" not declared in the current scope.
          at: GDScript::reload (res://Singletons/Steam/SteamManager.gd:11)
```

```
SCRIPT ERROR: Parse Error: Could not find type "SteamMultiplayerPeer" in the current scope.
          at: GDScript::reload (res://Singletons/Steam/SteamNetworkManager.gd:4)
```

Am I missing something? I would have thought this would have worked out of the box.

Below is my YAML file.

```yaml
name: Godot CI

on:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.3
  PROJECT_PATH: .

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --verbose --headless --export-release "Windows 64-bit" ./
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --verbose --headless --export-release "Linux 64-bit" ./
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux
```
