### ISSUE TITLE
Gitlab Pages

### ISSUE THREAD

**Issue by Waaflee** [aBARICHELLO/godot-ci#3]
Currently I'm trying to use your image in gitlab ci/cd to deploy the game in gitlab pages. The game is exported and the artifact uploaded but the page it's not being served. You know anything about it? I'm sorry I know this isn't the propper channel but I couldn't find any answer so far.

```yaml
image: barichello/godot-ci:3.1.1

variables:
  EXPORT_NAME: Hormiga de Langhton

stages:
  - build

web:
  stage: build
  script:
    - mkdir public
    - godot -v --export HTML5 public/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
    - public
  only:
    - master
```
