### ISSUE TITLE
Android CI is not implemented in older Docker images (<= 3.2.3)

### ISSUE THREAD

**Issue by 2shady4u** [aBARICHELLO/godot-ci#36]
I'm probably missing something here...?

When running the Android Debug job on Gitlab-CI I get following error:
![image](https://user-images.githubusercontent.com/42484461/96119374-2d00d780-0eed-11eb-8bd3-05e8cfa32f17.png)

Is there a gitlab variable I'm missing somewhere? If yes, which one and could this then be updated in the README?

my yml:
```
# Android Debug Job. It will use the generated debug.keystore. 
android_debug:
  stage: export
  script:
    - mkdir -v -p build/android
    - cd godot_project
    - godot -v --export-debug "Android Debug" ../build/android/$EXPORT_NAME-debug.apk
    - test -e ../build/android/$EXPORT_NAME-debug.apk
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/android
  only:
    - master
```

What am I missing here?
