### ISSUE TITLE
Recommended way to get SVG support (or install anything at all)

### ISSUE THREAD

**Issue by 2shady4u** [aBARICHELLO/godot-ci#8]
Hello, thank you for this repo!
I was wondering how to add SVG load support inside of the VM, because I'm getting these errors at the moment:
![Capture](https://user-images.githubusercontent.com/42484461/75344513-0d079f80-589b-11ea-9858-90bc1afa39b6.PNG)

I tried the following, but installing with apt-get doesn't seem to work:
```
image: barichello/godot-ci:3.2

stages:
  - export

before_script:
  - mkdir -v -p build/windows

windows:
  stage: export
  script:
    - apt-get update -y
    - apt-get install -y gwenview
    - cd GodotProject
    - godot -v --export-debug "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
    - test -e ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  only:
      - master
```

Any idea how I should do this?
