### ISSUE TITLE
mv: cannot stat '/root/.local/share/godot/templates/3.4.4.stable': No such file or directory

### ISSUE THREAD

**Issue by onepersonhere** [abarichello/godot-ci#87]
Steps to reproduce:
[in .yml]
```
name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.4.4
  EXPORT_NAME: export_name

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows
```
Error @Setup
```
Run mkdir -v -p ~/.local/share/godot/templates
  mkdir -v -p ~/.local/share/godot/templates
  mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
  shell: sh -e {0}
  env:
    GODOT_VERSION: 3.4.4
    EXPORT_NAME: test-project
mkdir: created directory '/github/home/.local'
mkdir: created directory '/github/home/.local/share'
mkdir: created directory '/github/home/.local/share/godot'
mkdir: created directory '/github/home/.local/share/godot/templates'
mv: cannot stat '/root/.local/share/godot/templates/3.4.4.stable': No such file or directory
Error: Process completed with exit code 1.
```
