### ISSUE TITLE
How to use with beta builds?

### ISSUE THREAD

**Issue by bend-n** [abarichello/godot-ci#89]
for instance [this](https://downloads.tuxfamily.org/godotengine/3.5/rc6)

I see https://github.com/abarichello/godot-ci/blob/651e66176ab66ba920d9487614fd472f470612a8/Dockerfile#L22-L24 however not quite sure how to set them. Do I `image: docker://barichello/godot-ci:3.5/rc6`?

**Comment by Calinou** [comment]
There are no container images provided for pre-releases.

**Comment by TheOrioli** [comment]
@bend-n your `GODOT_VERSION` is still set to 3.4.4 in the workflow, change that to ` GODOT_VERSION: 3.5.rc6`

**Comment by TheOrioli** [comment]
@bend-n this is the setup step in my builds
```yaml
 - name: Setup
      shell: bash
      run: |
        mkdir -v -p ~/.local/share/godot/templates
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.mono ~/.local/share/godot/templates/${GODOT_VERSION}.mono
```

I use the mono version, so it should be just removing the `.mono` at the end of the lines
