### ISSUE TITLE
cd: can't cd to EXPORT_NAME

### ISSUE THREAD

**Issue by Latrolage** [abarichello/godot-ci#96]
My godot-ci.yml is this:
```
name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: projectname

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $EXPORT_NAME
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $EXPORT_NAME
          godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
```
When it runs, it tells me
```shell
Run mkdir -v -p build/linux
  mkdir -v -p build/linux
  cd $EXPORT_NAME
  godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
  shell: sh -e {0}
  env:
    GODOT_VERSION: 3.5.1
    EXPORT_NAME: projectname
mkdir: created directory 'build'
mkdir: created directory 'build/linux'
/__w/_temp/1f01220c-db11-4904-9edd-ad229422adc9.sh: 2: cd: can't cd to projectname
```
